import React from 'react'

const Grid = () => {
  return (

    //  row-span and col-span use
    <div>
        <div className=' bg-gray-100  size-full grid grid-cols-4  *:p-20  *:border-2 *:border-amber-950 *:border-solid  gap-2'>
        {/* <div className=" col-span-3 bg-green-100">1</div> */}
        <div className="  bg-blue-100">1</div>
        {/* <div className="  bg-green-200 row-span-10 col-span-2">2</div> */}
        <div className="  bg-blue-300">3</div>
        <div className="  bg-green-300">3</div>
        <div className="  bg-blue-500">5</div>
        <div className="  bg-green-400">4</div>
        <div className="  bg-blue-200">2</div>
        <div className="  bg-green-500">5</div>
        <div className="  bg-blue-400">4</div>
        <div className="  bg-green-600">6</div>
        <div className="  bg-blue-600">6</div>
        <div className="  bg-green-100">1</div>
        <div className="  bg-blue-100">1</div>
        <div className="  bg-green-200">2</div>
        <div className="  bg-blue-300">3</div>
        <div className="  bg-green-300">3</div>
        <div className="  bg-blue-500">5</div>
        <div className="  bg-green-400">4</div>
        <div className="  bg-blue-200">2</div>
        <div className="  bg-green-500">5</div>
        <div className="  bg-blue-400">4</div>
        <div className="  bg-green-600">6</div>
        <div className="  bg-blue-600">6</div>
        <div className="  bg-green-100">1</div>
        <div className="  bg-blue-100">1</div>
        <div className="  bg-green-200">2</div>
        <div className="  bg-blue-300">3</div>
        <div className="  bg-green-300">3</div>
        <div className="  bg-blue-500">5</div>
        <div className="  bg-green-400">4</div>
        <div className="  bg-blue-200">2</div>
        <div className="  bg-green-500">5</div>
        <div className="  bg-blue-400">4</div>
        <div className="  bg-green-600">6</div>
        <div className="  bg-blue-600">6</div>
        <div className="  bg-green-100">1</div>
        <div className="  bg-blue-100">1</div>
        <div className="  bg-green-200">2</div>
        <div className="  bg-blue-300">3</div>
        <div className="  bg-green-300">3</div>
        <div className="  bg-blue-500">5</div>
        <div className="  bg-green-400">4</div>
        <div className="  bg-blue-200">2</div>
        <div className="  bg-green-500">5</div>
        <div className="  bg-blue-400">4</div>
        <div className="  bg-green-600">6</div>
        <div className="  bg-blue-600">6</div>
        <div className="  bg-green-100">1</div>
        <div className="  bg-blue-100">1</div>
        <div className="  bg-green-200">2</div>
        <div className="  bg-blue-300">3</div>
        <div className="  bg-green-300">3</div>
        <div className="  bg-blue-500">5</div>
        <div className="  bg-green-400">4</div>
        <div className="  bg-blue-200">2</div>
        <div className="  bg-green-500">5</div>
        <div className="  bg-blue-400">4</div>
        <div className="  bg-green-600">6</div>
        <div className="  bg-blue-600">6</div>
        <div className="  bg-green-100">1</div>
        <div className="  bg-blue-100">1</div>
        <div className="  bg-green-200">2</div>
        <div className="  bg-blue-300">3</div>
        <div className="  bg-green-300">3</div>
        <div className="  bg-blue-500">5</div>
        <div className="  bg-green-400">4</div>
        <div className="  bg-blue-200">2</div>
        <div className="  bg-green-500">5</div>
        <div className="  bg-blue-400">4</div>
        <div className="  bg-green-600">6</div>
        <div className="  bg-blue-600">6</div>
        <div className="  bg-green-100">1</div>
        <div className="  bg-blue-100">1</div>
        <div className="  bg-green-200">2</div>
        <div className="  bg-blue-300">3</div>
        <div className="  bg-green-300">3</div>
        <div className="  bg-blue-500">5</div>
        <div className="  bg-green-400">4</div>
        <div className="  bg-blue-200">2</div>
        <div className="  bg-green-500">5</div>
        <div className="  bg-blue-400">4</div>
        <div className="  bg-green-600">6</div>
        <div className="  bg-blue-600">6</div>
        <div className="  bg-green-100">1</div>
        <div className="  bg-blue-100">1</div>
        <div className="  bg-green-200">2</div>
        <div className="  bg-blue-300">3</div>
        <div className="  bg-green-300">3</div>
        <div className="  bg-blue-500">5</div>
        <div className="  bg-green-400">4</div>
        <div className="  bg-blue-200">2</div>
        <div className="  bg-green-500">5</div>
        <div className="  bg-blue-400">4</div>
        <div className="  bg-green-600">6</div>
        <div className="  bg-blue-600">6</div>
        <div className="  bg-green-100">1</div>
        <div className="  bg-blue-100">1</div>
        <div className="  bg-green-200">2</div>
        <div className="  bg-blue-300">3</div>
        <div className="  bg-green-300">3</div>
        <div className="  bg-blue-500">5</div>
        <div className="  bg-green-400">4</div>
        <div className="  bg-blue-200">2</div>
        <div className="  bg-green-500">5</div>
        <div className="  bg-blue-400">4</div>
        <div className="  bg-green-600">6</div>
        <div className="  bg-blue-600">6</div>
        <div className="  bg-green-100">1</div>
        <div className="  bg-blue-100">1</div>
        <div className="  bg-green-200">2</div>
        <div className="  bg-blue-300">3</div>
        <div className="  bg-green-300">3</div>
        <div className="  bg-blue-500">5</div>
        <div className="  bg-green-400">4</div>
        <div className="  bg-blue-200">2</div>
        <div className="  bg-green-500">5</div>
        <div className="  bg-blue-400">4</div>
        <div className="  bg-green-600">6</div>
        <div className="  bg-blue-600">6</div>
        <div className="  bg-green-100">1</div>
        <div className="  bg-blue-100">1</div>
        <div className="  bg-green-200">2</div>
        <div className="  bg-blue-300">3</div>
        <div className="  bg-green-300">3</div>
        <div className="  bg-blue-500">5</div>
        <div className="  bg-green-400">4</div>
        <div className="  bg-blue-200">2</div>
        <div className="  bg-green-500">5</div>
        <div className="  bg-blue-400">4</div>
        <div className="  bg-green-600">6</div>
        <div className="  bg-blue-600">6</div>
        <div className="  bg-green-100">1</div>
        <div className="  bg-blue-100">1</div>
        <div className="  bg-green-200">2</div>
        <div className="  bg-blue-300">3</div>
        <div className="  bg-green-300">3</div>
        <div className="  bg-blue-500">5</div>
        <div className="  bg-green-400">4</div>
        <div className="  bg-blue-200">2</div>
        <div className="  bg-green-500">5</div>
        <div className="  bg-blue-400">4</div>
        <div className="  bg-green-600">6</div>
        <div className="  bg-blue-600">6</div>
       
      </div>
    </div>
  )
}

export default Grid
